<?xml version="1.0"?>
<package format="3">
  <name>secure_patrol</name>
  <version>0.0.1</version>
  <description>
    Analysing navigation performance of autonomous robots
    when applying different privacy filters over sensor feeds.
  </description>
  <maintainer email="raywangruihua@gmail.com">Ray Wang Rui Hua</maintainer>
  <license>Apache 2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>action_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rtabmap_slam</exec_depend>
  <exec_depend>rtabmap_sync</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>